# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vY5aHqG9eQ8n40lZ_JtHsNcicDcLcKe

#IMPORTING THE LIBRARIES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#ACCESSING THE DATASET"""

dataset=pd.read_csv('covid.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

"""#SPLITTING THE DATASET INTO TEST SET AND TRAINING SET"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=1/3,random_state=0)
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

"""#TRAINING THE SIMPLE REGRESSION MODEL ON THE TRAINING SET"""

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

"""#PREDICTING THE TEST SET RESULTS"""

Y_pred=regressor.predict(X_test)
print(Y_pred)

"""#VISUALIZING THE TRAINING SET RESULTS"""

plt.scatter(X_train,Y_train,color="red")
plt.plot(X_train,regressor.predict(X_train),color="blue")
plt.title("NEW CASES VS ACTIVE CASES(TRAINING SET)")
plt.xlabel("ACTIVE CASES")
plt.ylabel("NEW CASES")
plt.show()

"""#VISUALIZING THE TEST SET"""

plt.scatter(X_test,Y_test,color="red")
plt.plot(X_test,Y_pred,color="blue")
plt.title("NEW CASES VS ACTIVE CASES(TEST SET)")
plt.xlabel("ACTIVE CASES")
plt.ylabel("NEW CASES")
plt.show()